name: example
author: Alexander Ryzhov <aryzhov07@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  timer_builder:
    path: ../

flutter:

  uses-material-design: true
